AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Report Service

Globals:
  Function:
    Runtime: python3.9

Parameters:
  ApiUrl:
    NoEcho: true
    Type: String
    Description: "REQUIRED: External API url for making requests"

  LakeBucketName:
    Type: String
    Description: "REQUIRED: Lake Bucket name"

Resources:
  CronFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Makes an API request on a schedule and uploads data to S3
      CodeUri: functions/cron/
      Handler: main.lambda_handler
      Timeout: 60
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 * * ? *) # every day at 5am
            Name: every-day-5am
      Environment:
        Variables:
          API_URL: !Ref ApiUrl
          LAKE_BUCKET_NAME: !Ref LakeBucketName
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              !Sub
                - "arn:aws:s3:::${BucketName}/*"
                - {BucketName: !Ref LakeBucketName}

  LakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LakeBucketName


  S3Function:
    Type: AWS::Serverless::Function
    Properties:
      Description: Reads new data from S3 and triggers glue crawler
      CodeUri: functions/s3/
      Handler: main.lambda_handler
      Timeout: 60
      Events:
        FileUploadToS3:
          Type: S3
          Properties:
            Bucket: !Ref LakeBucket
            Events: s3:ObjectCreated:*
            Filter: 
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.json'
      Environment:
        Variables:
          LAKE_BUCKET_NAME: !Ref LakeBucketName
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              !Sub
                - "arn:aws:s3:::${BucketName}/*"
                - {BucketName: !Ref LakeBucketName}
